FROM mongo:4.2.2

COPY ./config/mongod.conf /etc/mongod.conf
# RUN /bin/bash -c "chmod 644 /etc/mongod.conf"
# RUN /bin/bash -c "chown mongodb:mongodb /etc/mongod.conf"

# RUN "mkdir -p /var/lib/mongodb"
# RUN /bin/bash -c "chown -R mongodb:mongodb /var/lib/mongodb"



